namespace BaseLayer.Application.Contracts;

public sealed record OAuthStartRequest(string Name, string BaseUrl);
public sealed record OAuthStartResult(string AuthorizationUrl, string State, DateTime ExpiresUtc);
public sealed record OAuthCompleteRequest(string Code, string State);
public sealed record HomeSettingsRequest(bool AllowAll, bool AllowFutureDevices, List<string> AllowedEntityIds, string? HouseholdPowerSensorId, Dictionary<string, string?> DevicePowerSensors, string PowerSource = "wholeHouseMeter", Dictionary<string, ThermostatLimits>? ThermostatLimits = null, Dictionary<string, string>? ShutoffLevels = null, bool? SmartPowerOffEnabled = null, Dictionary<string, EvChargingSettings?>? EvCharging = null);
public sealed record EvChargingSettings(string CurrentEntityId, double WattsPerAmp = 240);
public sealed record CurrentControlDto(string EntityId, string Name, double? Amps, double Min, double Max, double Step);
public sealed record EvCurrentRequest(string EntityId, double Amps, string IdempotencyKey);
public sealed record SmartPowerOffRequest(bool Enabled);
public sealed record ThermostatLimits(double MinF = 66, double MaxF = 80);
public sealed record CircuitPriorityDto(string EntityId, string? Priority, List<string> Options);
public sealed record CircuitPriorityRequest(string EntityId, string Priority, string IdempotencyKey);
public sealed record CircuitCommandRequest(string EntityId, string Action, string IdempotencyKey);
public sealed record TurnOffRequest(List<string> EntityIds, string IdempotencyKey);
public sealed record PowerSensorDto(string EntityId, string Name, string Unit);
public sealed record DeviceDto(string EntityId, string Name, string State, double? PowerWatts, bool Allowed, bool Recommended, string? PowerSensorId, double ThermostatMinF = 66, double ThermostatMaxF = 80, string ShutoffLevel = "Sometimes", bool IsCircuit = false, EvChargingSettings? EvCharging = null, CurrentControlDto? EvCurrent = null, CircuitPriorityDto? CircuitPriority = null);
public sealed record CommandDto(Guid Id, string EntityId, string Status, int Attempts, DateTime CreatedUtc, string? Message, bool Automatic = false, string Action = "Off", double? CurrentAmps = null, string? CircuitPriority = null, double? PreviousCurrentAmps = null, bool IsRestoration = false);
public sealed record HomeDto(Guid Id, string Name, bool Connected, bool Revoked, DateTime? LastSeenUtc, double? HouseholdWatts, double LimitWatts, double? ProjectedWatts, List<DeviceDto> Devices, List<CommandDto> Commands, string BaseUrl, string? HouseholdPowerSensorId, bool AllowFutureDevices, List<PowerSensorDto> PowerSensors, string PowerSource = "wholeHouseMeter", bool SmartPowerOffEnabled = false, string SmartPowerOffStatus = "off", List<RestoreQueueDto>? RestoreQueue = null, List<CurrentControlDto>? CurrentControls = null);
public sealed record RestoreQueueDto(string EntityId, string Name, double? EstimatedWatts, DateTime QueuedUtc, string Status, double? CurrentAmps = null, double? TargetAmps = null);
